name: u_net
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0=py313haa95532_0
  - aom=3.6.0=hd77b12b_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - contourpy=1.3.1=py313h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py313h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.10=h62dcd97_0
  - gitdb=4.0.12=py313haa95532_0
  - gitpython=3.1.43=py313haa95532_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - idna=3.7=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.8=py313h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libclang13=20.1.8=default_hccbf073_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libllvm20=20.1.8=h3aa9ab2_0
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.50=h7351971_1
  - libpq=17.4=h4a159e6_2
  - libre2-11=2024.07.02=h5da7b33_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libxslt=1.1.41=h0739af5_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.7=py313hfa70ccb_0
  - matplotlib-base=3.10.7=py313he1ded55_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=1.3.11=py313h5810407_1
  - mkl_random=1.2.8=py313hedd7022_1
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - numpy=2.3.3=py313h050da96_1
  - numpy-base=2.3.3=py313h1e017a8_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py313hb328d1f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py313haa95532_0
  - protobuf=5.29.3=py313h5da7b33_0
  - psutil=7.0.0=py313h02ab6af_0
  - pycparser=2.23=py313haa95532_0
  - pydantic=2.12.2=py313haa95532_0
  - pydantic-core=2.41.4=py313h114bc41_0
  - pyparsing=3.2.0=py313haa95532_0
  - pyside6=6.9.2=py313h151a370_0
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.7=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python_abi=3.13=1_cp313
  - pyyaml=6.0.2=py313h827c3e9_0
  - qhull=2020.2=h59b6b97_2
  - qtbase=6.9.2=hd965823_1
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hebbe641_0
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - requests=2.32.5=py313haa95532_0
  - sentry-sdk=2.18.0=py313haa95532_0
  - setproctitle=1.3.6=py313h02ab6af_0
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py313h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing=3.10.0.0=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing-inspection=0.4.2=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wandb=0.22.2=py313hf61f64f_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.5
      - sympy==1.14.0
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
prefix: C:\Users\lkfu5\anaconda3\envs\u_net
